### ISSUE TITLE
wrong polynomial coefficients in cQuarticPoly.m

### ISSUE THREAD

**Issue by KexianShen** [fjp/frenet#5]
Some polynomial coefficients are wrong in cQuarticPoly.m.

It should be:

line 30: x = obj.c(2) + 2 * obj.c(3).*t + 3 * obj.c(4).*t.^2 + 4 * obj.c(5).*t.^3;

line 34: x = 2 * obj.c(3) + 6 * obj.c(4).*t + 12 * obj.c(5).*t.^2;

**Comment by fjp** [comment]
Nice catch @KexianShen and thank you for opening a new issue. 

You are also welcome to make a pull request. Otherwise, I'll fix this mistake by the end of this week. 

Thanks again for your contribution.

**Comment by KexianShen** [comment]
You are welcome, I have made a pull request, please check that.
